// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataForm: typeof import('./../src/components/DataForm/index.vue')['default']
    DialogForm: typeof import('./../src/components/DialogForm/index.vue')['default']
    IconSelect: typeof import('./../src/components/IconSelect/index.vue')['default']
    Index2: typeof import('./../src/components/DataForm/index2.vue')['default']
    Index3: typeof import('./../src/components/IconSelect/index3.vue')['default']
    MyIcon: typeof import('./../src/components/MyIcon/index.vue')['default']
    PageList: typeof import('./../src/components/PageList/index.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/index.vue')['default']
    ParentView: typeof import('./../src/components/ParentView/index.vue')['default']
    RadioDictData: typeof import('./../src/components/RadioDictData/index.vue')['default']
    RightKeyMenu: typeof import('./../src/components/RightKeyMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDictData: typeof import('./../src/components/SelectDictData/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TEnhancedTable: typeof import('tdesign-vue-next')['EnhancedTable']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
